import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import {ChakraProvider, CSSReset, Box} from '@chakra-ui/react';
import SearchForm from './hotelSearch/searchForm';

//<Head> Tag is for the text u see in ur tab or for description of your page, can contain metadata for search engine as well
//Main point, is for developers to see, not users


export default function Home() {
  return (
      <ChakraProvider>
          <div className={styles.container}>
              <Head>
                  <title>Search for hotel</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              {/*<h1>Main Search Page, implement search bar and search feature here...</h1>*/}
          </div>
          <SearchForm />
      </ChakraProvider>
  )
}
