import Head from 'next/head'
import styles from '../styles/Home.module.css'
//<Head> Tag is for the text u see in ur tab or for description of your page, can contain metadata for search engine as well
//Main point, is for developers to see, not users
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home Page</h1>
    </div>
  )
}
